import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFilePlus,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconMessageCircle,
  IconTable,
  IconBrain,
  IconSearch,
  IconLock,
  IconChartLine,
  IconChartBar,
  IconCamera,
  IconCalendar,
} from "@tabler/icons-react";

export type Icon = React.ComponentType<IconProps>;

export const Icons: Record<string, Icon> = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  filePlus: IconFilePlus,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  chat: IconMessageCircle,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  pill: IconTable,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  lineChart: IconChartLine,
  barChart2: IconChartBar,
  alertTriangle: IconAlertTriangle,
  brain: IconBrain,
  search: IconSearch,
  lock: IconLock,
  sliders: IconSettings,
  camera: IconCamera,
  appointment: IconCalendar,
};
